### ISSUE TITLE
Rendering screen overflows on certain screen sizes.

### ISSUE THREAD

**Issue by jmkraut** [kressnick25/pointfluent#6]
Sometimes overflows screen size in debug mode.
![image](https://user-images.githubusercontent.com/49256848/90971225-0bb8e600-e551-11ea-9b0e-ba1296bb825d.png)

ERROR:

![image](https://user-images.githubusercontent.com/49256848/90971259-808c2000-e551-11ea-91a5-a5f0acade92b.png)

**Comment by kressnick25** [comment]
Change this child to a SingleChildScrollView(), and make this Column() the child of it. 
https://www.youtube.com/watch?v=2E9iZgg5TOY
This makes the login screen scrollable, which solves the bottom overflow.
Like this:
![Screen Shot 2020-09-05 at 15 51 07](https://user-images.githubusercontent.com/24802707/92298777-a7a21300-ef8f-11ea-86d8-2cfc1bc4283b.png)

_Originally posted by @yuk0ga in https://github.com/kressnick25/pointfluent/pull/11#discussion_r483914970_
